import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Aurora from "@/components/Aurora";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* //absolute to fixed */}
        <div className="fixed inset-0 top-0 z-[-1] min-h-screen"> 
          <Aurora
            colorStops={["#2054ff", "#b51fe0", "#3910f2"]}
            blend={0.5}
            amplitude={1.0}
            speed={0.5}
          />
        </div>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
